/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested, IsDate } from "class-validator";
import { ApplicationCreateNestedManyWithoutStudentsInput } from "./ApplicationCreateNestedManyWithoutStudentsInput";
import { Type } from "class-transformer";
import { AppointmentCreateNestedManyWithoutStudentsInput } from "./AppointmentCreateNestedManyWithoutStudentsInput";
import { RoadMapCreateNestedManyWithoutStudentsInput } from "./RoadMapCreateNestedManyWithoutStudentsInput";

@InputType()
class StudentCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => ApplicationCreateNestedManyWithoutStudentsInput,
  })
  @ValidateNested()
  @Type(() => ApplicationCreateNestedManyWithoutStudentsInput)
  @IsOptional()
  @Field(() => ApplicationCreateNestedManyWithoutStudentsInput, {
    nullable: true,
  })
  applications?: ApplicationCreateNestedManyWithoutStudentsInput;

  @ApiProperty({
    required: false,
    type: () => AppointmentCreateNestedManyWithoutStudentsInput,
  })
  @ValidateNested()
  @Type(() => AppointmentCreateNestedManyWithoutStudentsInput)
  @IsOptional()
  @Field(() => AppointmentCreateNestedManyWithoutStudentsInput, {
    nullable: true,
  })
  appointments?: AppointmentCreateNestedManyWithoutStudentsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dateOfBirth?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string | null;

  @ApiProperty({
    required: false,
    type: () => RoadMapCreateNestedManyWithoutStudentsInput,
  })
  @ValidateNested()
  @Type(() => RoadMapCreateNestedManyWithoutStudentsInput)
  @IsOptional()
  @Field(() => RoadMapCreateNestedManyWithoutStudentsInput, {
    nullable: true,
  })
  roadMaps?: RoadMapCreateNestedManyWithoutStudentsInput;
}

export { StudentCreateInput as StudentCreateInput };
