/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { RoadMap } from "./RoadMap";
import { RoadMapCountArgs } from "./RoadMapCountArgs";
import { RoadMapFindManyArgs } from "./RoadMapFindManyArgs";
import { RoadMapFindUniqueArgs } from "./RoadMapFindUniqueArgs";
import { CreateRoadMapArgs } from "./CreateRoadMapArgs";
import { UpdateRoadMapArgs } from "./UpdateRoadMapArgs";
import { DeleteRoadMapArgs } from "./DeleteRoadMapArgs";
import { UniversityFindManyArgs } from "../../university/base/UniversityFindManyArgs";
import { University } from "../../university/base/University";
import { Student } from "../../student/base/Student";
import { RoadMapService } from "../roadMap.service";
@graphql.Resolver(() => RoadMap)
export class RoadMapResolverBase {
  constructor(protected readonly service: RoadMapService) {}

  async _roadMapsMeta(
    @graphql.Args() args: RoadMapCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [RoadMap])
  async roadMaps(
    @graphql.Args() args: RoadMapFindManyArgs
  ): Promise<RoadMap[]> {
    return this.service.roadMaps(args);
  }

  @graphql.Query(() => RoadMap, { nullable: true })
  async roadMap(
    @graphql.Args() args: RoadMapFindUniqueArgs
  ): Promise<RoadMap | null> {
    const result = await this.service.roadMap(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => RoadMap)
  async createRoadMap(
    @graphql.Args() args: CreateRoadMapArgs
  ): Promise<RoadMap> {
    return await this.service.createRoadMap({
      ...args,
      data: {
        ...args.data,

        student: args.data.student
          ? {
              connect: args.data.student,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => RoadMap)
  async updateRoadMap(
    @graphql.Args() args: UpdateRoadMapArgs
  ): Promise<RoadMap | null> {
    try {
      return await this.service.updateRoadMap({
        ...args,
        data: {
          ...args.data,

          student: args.data.student
            ? {
                connect: args.data.student,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => RoadMap)
  async deleteRoadMap(
    @graphql.Args() args: DeleteRoadMapArgs
  ): Promise<RoadMap | null> {
    try {
      return await this.service.deleteRoadMap(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [University], { name: "universities" })
  async findUniversities(
    @graphql.Parent() parent: RoadMap,
    @graphql.Args() args: UniversityFindManyArgs
  ): Promise<University[]> {
    const results = await this.service.findUniversities(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Student, {
    nullable: true,
    name: "student",
  })
  async getStudent(@graphql.Parent() parent: RoadMap): Promise<Student | null> {
    const result = await this.service.getStudent(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
